### ISSUE TITLE
Allow for custom endpoints

### ISSUE THREAD

**Issue by sebromero** [AnthonyMDev/AmazonS3RequestManager#20]
I use a self hosted LibreS3 installation which provides S3 API REST compatibility. However the library currently doesn't allow for custom endpoints since the region parameter is an immutable enum.
I suggest that we either change the region to be a plain string and use something like `.USStandard.rawValue` when calling the initialiser or we introduce a `host` property that has priority over the `region` property. Other ideas?

**Comment by AnthonyMDev** [comment]
@sbhklr That's a great point. Due to some changes with V4Signatures (#17), we actually need to have multiple values that are being determined by the `region`. The `endpoint` and the `name` of the region are both used now. This complicates things just a little. You can see the [feature/AWS_signature_v4](https://github.com/AnthonyMDev/AmazonS3RequestManager/tree/feature/AWS_signature_v4) branch to see what I'm talking about.

Let me look more closely at what I'm doing there and we can discuss what the best solution to this is.

**Comment by sebromero** [comment]
I see. I'm thinking about an elegant solution. Looks like enums aren't really suited for injecting custom values.

**Comment by AnthonyMDev** [comment]
Not true, you can use associated values on an enum case. The most elegant way to do this would probably be to create a new region enum case `Custom` with associated values for the endpoint and name.

**Comment by sebromero** [comment]
Alright, I didn't know. That's indeed a pretty elegant solution.

**Comment by sebromero** [comment]
Hmm, looks like we cannot mix enum cases with raw values and associated values.

**Comment by AnthonyMDev** [comment]
Ah, that's right. Didn't think about that. I should be able to fix this by removing the raw values from the enum. We don't really need them. I'll get that done tomorrow!

**Comment by AnthonyMDev** [comment]
Okay, I've removed the raw values from the enum case on `develop`. Next step is to add the custom region case.

**Comment by AnthonyMDev** [comment]
This has been implemented in version `0.12.0`

**Comment by AnthonyMDev** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

anthony.miller.csn@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Resources:

What is empowr?
Who's behind it?
See who you know that's on empowr

No more emails from anthony.miller.csn@gmail.com (anthony.miller.csn@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnSlOP%2BykL1iZ8FolutCW1PIj0DB2XI3qdRR8Y%2F83dGPTh%2BE1Om81Y%2FBo9A%2Fr5YdewFmsb2VEFcqhiAz1KjnUcJaFCPtdvi%2BeZyQJ%2BbX2ackmaUU2t2xyO5Fixga8UkD%2FcGsOZttzOEtb&vet=694&mlid=8998498434&fn=QpLpyL23t7HpRXkzIHngtg%3D%3D

*This offer has been sent by anthony.miller.csn@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.

**Comment by sbhklr** [comment]
@AnthonyMDev Dude, has your account been pwnd?

**Comment by AnthonyMDev** [comment]
Yeah something weird happened. It may be malware or a bug in a legitimate 3rd party service I use. Looking into it.

**Comment by AnthonyMDev** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

Yesterday, anthony.miller.csn@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Not sure you know anthony.miller.csn@gmail.com?

View their photos  to see if you recognize them

Resources:

What is empowr?
Who's behind it?
See who you know that's on empowr

No more emails from anthony.miller.csn@gmail.com (anthony.miller.csn@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnSlOP%2BykL1iZ8FolutCW1PIj0DB2XI3qdRR8Y%2F83dGPTh%2BE1Om81Y%2FBo9A%2Fr5YdewFmsb2VEFcqhiAz1KjnUcJaFCPtdvi%2BeZyQJ%2BbX2ackmaUU2t2xyO5Fixga8UkD%2FcGsOZttzOEtb&vet=694&mlid=9006480757&fn=QpLpyL23t7HpRXkzIHngtg%3D%3D

*This offer has been sent by anthony.miller.csn@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.

**Comment by AnthonyMDev** [comment]
#outlook a {

padding: 0;
}
ReadMsgBody {

width: 100%;
}
ExternalClass {

width: 100%;
}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
appleFooter a {

color: #999999;

text-decoration: none;
}
faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

Just a friendly reminder that anthony.miller.csn@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Don't know anthony.miller.csn@gmail.com?

Return the $20  so it doesn't go to waste and you're not keeping anthony.miller.csn@gmail.com waiting

Resources:

What is empowr?
Who's behind it?
See who you know that's on empowr

No more emails from anthony.miller.csn@gmail.com (anthony.miller.csn@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnSlOP%2BykL1iZ8FolutCW1PIj0DB2XI3qdRR8Y%2F83dGPTh%2BE1Om81Y%2FBo9A%2Fr5YdewFmsb2VEFcqhiAz1KjnUcJaFCPtdvi%2BeZyQJ%2BbX2ackmaUU2t2xyO5Fixga8UkD%2FcGsOZttzOEtb&vet=694&mlid=9014714465&fn=QpLpyL23t7HpRXkzIHngtg%3D%3D

*This offer has been sent by anthony.miller.csn@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.

**Comment by AnthonyMDev** [comment]
body {{ margin:0 !important; }}
div[style*="margin: 16px 0"] {{ margin:0 !important; font-size:100% !important; }}
#outlook a {{

padding: 0;
}}
ReadMsgBody {{

width: 100%;
}}
ExternalClass {{

width: 100%;
}}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {{

line-height: 100%;
}}
body, table, td, a {{

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}}
table, td {{

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}}
img {{

-ms-interpolation-mode: bicubic;
}}

body {{margin: 0;padding: 0;}}
img {{

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}}
table {{

border-collapse: collapse !important;
}}
body {{

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}}

appleBody a {{

color: #68440a;

text-decoration: none;
}}
appleFooter a {{

color: #999999;

text-decoration: none;
}}
faq {{

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}}
mobile-only {{

display: none;
}}
img-apps {{ padding:0 5px 0 0;}}

a.mobile-button:link, a.mobile-button:visited {{ color:#fff!important;}}

@media screen and (max-width: 525px) {{

table[class="wrapper"] {{

width: 100% !important;
}}

td[class="logo"] {{

text-align: left;

padding: 20px 0 20px 0 !important;
}}
td[class="logo"] img {{

margin: 0 auto!important;
}}

[class="mobile-only"] {{

display: block;
}}

br[class="mobile-hide"] {{

display: none;
}}
td[class="mobile-hide"] {{

display: none;
}}
img[class="mobile-hide"] {{

display: none !important;
}}
img[class="img-max"] {{

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}}

img[class="img-min"] {{

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}}

img[class="img-apps"] {{

max-width: 46% !important;

width: 46% !important;

height: auto !important;

padding:0 2px;
}}
img[class="img-max-profile"] {{

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}}

table[class="responsive-table"] {{

width: 100%!important;
}}

td[class="padding"] {{

padding: 10px 5% 15px 5% !important;
}}
td[class="amount"] {{

font-size: 9px!important;
}}
td[class="mobile-text-twelve"] {{

font-size: 12px!important;
}}
span[class="mobile-text-twelve"] {{

font-size: 14px!important;
}}
td[class="padding-copy"] {{

padding: 10px 5% 10px 5% !important;

text-align: center;
}}
td[class="padding-meta"] {{

padding: 30px 5% 0px 5% !important;

text-align: center;
}}
td[class="no-pad"] {{

padding: 0 0 20px 0 !important;
}}
td[class="no-pad-bottom"] {{

padding: 25px 0 0 0 !important;
}}
td[class="no-padding"] {{

padding: 0 !important;
}}
td[class="section-padding"] {{

padding: 25px 15px 25px 15px !important;
}}
td[class="section-no-padding-bottom"] {{

padding: 25px 15px 0 15px !important;
}}

td[class="section-no-padding-top"] {{

padding: 0 5% 25px 5% !important;
}}

td[class="section-no-padding-top-bottom"] {{

padding: 0 5% 0 5% !important;
}}
td[class="section-padding-bottom-image"] {{

padding: 50px 15px 0 15px !important;
}}

td[class="mobile-wrapper"] {{

padding: 10px 5% 15px 5% !important;
}}
table[class="mobile-button-container"] {{

margin: 0 auto;

width: 100% !important;
}}
a[class="mobile-button"] {{

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}}
}}

Earn $100 in 1 minute.

How?

Simply try our new social network for only 50 seconds...

..and give us your feedback in less than 10 seconds.

Give me $100 (start the clock) &#9658;

Your empowr account was reserved for you by anthony.miller.csn@gmail.com. In order to store your gift however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything.

While your account is very new, if you fail to sign in for just a few days, it will be deleted to eliminate unwanted emails for you, so click a button in emails periodically to notify the system of your desire to keep it active. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnSlOP%2BykL1iZ8FolutCW1PIj0DB2XI3qdRR8Y%2F83dGPTh%2BE1Om81Y%2FBo9A%2Fr5YdewFmsb2VEFcqhiAz1KjnUcJaFCPtdvi%2BeZyQJ%2BbX2ackmaUU2t2xyO5Fixga8UkD%2FcGsOZttzOEtb&vet=724&mlid=9313073043.

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: empowr Terms and Conditions. You can prevent future emails here. You can change your password here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by AnthonyMDev** [comment]
body { margin:0 !important; }
div[style*="margin: 16px 0"] { margin:0 !important; font-size:100% !important; }
#outlook a {

padding: 0;
}
ReadMsgBody {

width: 100%;
}
ExternalClass {

width: 100%;
}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {margin: 0;padding: 0;}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
appleFooter a {

color: #999999;

text-decoration: none;
}
faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
mobile-only {

display: none;
}
img-apps { padding:0 5px 0 0;}

a.mobile-button:link, a.mobile-button:visited { color:#fff!important;}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;

padding:0 2px;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 9px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

has invited you to this exclusive free trial
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=15&amp;authToken=%2f1gCEGV9d6c%2bVY%2b1oJCzGEpDnPJjhne%2bdYYhbdMMz%2fPsiFQmKWAnh3168Z1zE52CCu2AW1j5g2Hqq4EAAGdEVN0C3bcvGgEYEmI1zTIVqdeZnTD2A9EBg74xoc%2bfNk9%2f3YeR0p0TFpMRR%2bcmJJ7eArVqmsXYNIEYcIR8JW6fRDiut%2f7tUzff%2fQd5QvHx3Q7ODlhL55lTB2idEogpH2%2fmCj81DyrzmBH8QmULVbF0oU3Rc2r5TK2iwnu5vTa32rTRraIkzQwZgplX8LMbYSAW0am3RYCxM%2bUdYfqbvmQoxIdMlH3R5hvwmAZPH0lTyq64&amp;PolicyAcceptance=hS9jQifr3fBH%2bKMoUM3K%2fVU2tv0EdFG%2bbo3Yz%2fYAc%2fplMUi0N4Nnc5ULQs6pcqBp78VwAR6i1KKqjIr7QqkxQKMQolSVrb5NksuGe2eQh%2bYjwKS2M%2bo6EcEZC4Nk8EE7ritkTu0LtDxYYrMbmY3in579dXZPmbomJOqM9OSk1%2fc4Jdz%2bh3tOX%2bVPwCIxtyRPZwJR3GVqoYX2oa%2bI1Wt%2fWteNKA97TiU2Pprmh5R0V4XiKtPjUJGeyHKL5JbXKaFo7u3D0sCIqQut4NJkm0M4ZkNGN0W98%2f2d1hHJUfQGPAPDpjXPPJpEdJbrLeHYcq1cef1X1fyx0SzQc9i6HP%2bbydTfQJfkPnh1LzNyU2DhppjMEDg03z%2bJS4Ypo1SwTfVm1odapt1YSSgUjMxqd9gmIxyRvrnwncj6ElKrd68oMwR7NOAoihuXgVYg3TwDLgd42okxLK75dfZ0FGicMQL9K7IP6k17OZbPBL3Ck2dCH1ZH67KMtElEeQbQH4ndhDMCjzMgpJoWFloE7%2bRJt%2f6glAZQL1tALuxsvAsexzHWFs0VcukYawo%2f4RP0D%2fzPOM8P%2fnllU71sRin5skWVyRU%2fe5Tk4vMVuUWmojM%2fNPjSvwwC7yh0YfaHo9Zyy506vdTaqaElGNUsbrPxEApwy4tiHwAsh1TwtNKGobkjtXDZOEoQP0P1cB4jlmHKWKQY3zwj1u9e2sBikVNdTxlaubTIUyD%2f2M%2fezzL1pS27iiY51qhOAAW38WkNJ8zTqgD3ifvRTuQY7Om9fEpkFURv5mAjdaypVcOtl5QSm8tESTFjoRGUZNHNcZhzpjhi8XhgSh1%2be9sgFhhz5n0FauJhR29QqxiTDu4%2bGGZ%2fTtMOppsHxwU3sLERvSed4X2d0TQkD9ahO4p%2f4DH%2bJ8Q%2fDJGo1YfrWC%2f0WAXnNbS2FufzmeqblaKkJs%2bE2gQW6kov4tbjSjF5XyhdZDwNDxWfm6oGhhh6Cg%3d%3d&amp;vet=745&amp;dt=111817&amp;mlid=10031189293&amp;tmpID=3340&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=40457919&amp;rt=13:

Your account was reserved for you by  in order to reserve your free trial, however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnSlOP%2BykL1iZ8FolutCW1PIj0DB2XI3qdRR8Y%2F83dGPTh%2BE1Om81Y%2FBo9A%2Fr5YdewFmsb2VEFcqhiAz1KjnUcJaFCPtdvi%2BeZyQJ%2BbX2ackmaUU2t2xyO5Fixga8UkD%2FcGsOZttzOEtb&vet=745&mlid=10031189293.

No more emails from  ()? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnSlOP%2BykL1iZ8FolutCW1PIj0DB2XI3qdRR8Y%2F83dGPTh%2BE1Om81Y%2FBo9A%2Fr5YdewFmsb2VEFcqhiAz1KjnUcJaFCPtdvi%2BeZyQJ%2BbX2ackmaUU2t2xyO5Fixga8UkD%2FcGsOZttzOEtb&vet=745&mlid=10031189293

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: empowr Terms and Conditions. You can prevent future emails here. You can change your password here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA
