### ISSUE TITLE
Feature Request: List Directory Contents

### ISSUE THREAD

**Issue by joehelton** [AnthonyMDev/AmazonS3RequestManager#6]
Hey Anthony. Thanks for the great library. 
Is it possible to use AmazonS3RequestManager to get a list of the contents of an S3 bucket or directory?

**Comment by AnthonyMDev** [comment]
@joehelton Thank you! 
There is! There is not currently a specific method in the library for this request, but you can use `amazonURLRequest(method: Alamofire.Method, path: String, subresource: String? = nil, acl: AmazonS3ACL? = nil) -> NSURLRequest` to serialize an `NSURLRequest` for the Amazon S3 service and then just pass that request through to `Alamofire.request(request: NSURLRequest)`.
Using this method, you can hit any of the REST APIs available through Amazon S3.

The API documents from Amazon are found here:
http://docs.aws.amazon.com/AmazonS3/latest/API/APIRest.html

**Comment by AnthonyMDev** [comment]
I'll also be looking into implementing a designated method to do this once #5 is completed.

**Comment by joehelton** [comment]
Great! Thanks so much for the help man.

**Comment by AnthonyMDev** [comment]
No problem! If you have any other questions or suggestions, please let me know!

**Comment by joehelton** [comment]
Hey Anthony. Thanks again for the help. 
I am getting a "SignatureDoesNotMatch" error when I try to do this. Would you mind posting a code sample I could use for comparison? Thanks.

**Comment by AnthonyMDev** [comment]
@joehelton Make sure that you have set the `bucket`, `region`, `access key`, and `secret` correctly on your `AmazonS3RequestManager` instance before calling this method. If you continue to have issues, please open another issue for this problem with more details of your implementation and I'll take a look.

Thanks!

**Comment by sebromero** [comment]
@joehelton I think it's a problem with the HTTP headers. I'm currently looking into this.

**Comment by AnthonyMDev** [comment]
@sbhklr I wasn't aware that this was an actual bug in the library, rather than a configuration issue. If you are experiencing an actual bug, would you please open a new issue for it? This issue is for an unrelated upcoming feature. Thanks for looking into this!

**Comment by ljesus** [comment]
I've implemented this feature in my branch https://github.com/ljesus/AmazonS3RequestManager using the "prefix" parameter as stated in AWS' documentation (http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html)

**Comment by sebromero** [comment]
Thx @ljesus , there is already a PR for this. See #38

**Comment by AnthonyMDev** [comment]
#outlook a {

padding: 0;
}
ReadMsgBody {

width: 100%;
}
ExternalClass {

width: 100%;
}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
appleFooter a {

color: #999999;

text-decoration: none;
}
faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

anthony.miller.csn@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Resources:

What is empowr?
Who's behind it?
See who you know that's on empowr

No more emails from anthony.miller.csn@gmail.com (anthony.miller.csn@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVndh%2BWZPozm1D8pGhgZPOKGLIcws7RZylhk7%2BFRFQivlX%2F4uVLGyj5zjGgqHmUsxkjUvEIQymJace5jm1BXmPyXJx57nLfmPDHs26jEDB5qS0LTPP6ZdiedqAfrnjfcmlrzACVf1NbBEq&vet=694&mlid=8998759049&fn=QpLpyL23t7HpRXkzIHngtg%3D%3D

*This offer has been sent by anthony.miller.csn@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.

**Comment by AnthonyMDev** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

Yesterday, anthony.miller.csn@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Not sure you know anthony.miller.csn@gmail.com?

View their photos  to see if you recognize them

Resources:

What is empowr?
Who's behind it?
See who you know that's on empowr

No more emails from anthony.miller.csn@gmail.com (anthony.miller.csn@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVndh%2BWZPozm1D8pGhgZPOKGLIcws7RZylhk7%2BFRFQivlX%2F4uVLGyj5zjGgqHmUsxkjUvEIQymJace5jm1BXmPyXJx57nLfmPDHs26jEDB5qS0LTPP6ZdiedqAfrnjfcmlrzACVf1NbBEq&vet=694&mlid=9006742222&fn=QpLpyL23t7HpRXkzIHngtg%3D%3D

*This offer has been sent by anthony.miller.csn@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.

**Comment by AnthonyMDev** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

Just a friendly reminder that anthony.miller.csn@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Don't know anthony.miller.csn@gmail.com?

Return the $20  so it doesn't go to waste and you're not keeping anthony.miller.csn@gmail.com waiting

Resources:

What is empowr?
Who's behind it?
See who you know that's on empowr

No more emails from anthony.miller.csn@gmail.com (anthony.miller.csn@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVndh%2BWZPozm1D8pGhgZPOKGLIcws7RZylhk7%2BFRFQivlX%2F4uVLGyj5zjGgqHmUsxkjUvEIQymJace5jm1BXmPyXJx57nLfmPDHs26jEDB5qS0LTPP6ZdiedqAfrnjfcmlrzACVf1NbBEq&vet=694&mlid=9014973094&fn=QpLpyL23t7HpRXkzIHngtg%3D%3D

*This offer has been sent by anthony.miller.csn@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.

**Comment by AnthonyMDev** [comment]
body {{ margin:0 !important; }}
div[style*="margin: 16px 0"] {{ margin:0 !important; font-size:100% !important; }}
#outlook a {{

padding: 0;
}}
.ReadMsgBody {{

width: 100%;
}}
.ExternalClass {{

width: 100%;
}}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {{

line-height: 100%;
}}
body, table, td, a {{

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}}
table, td {{

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}}
img {{

-ms-interpolation-mode: bicubic;
}}

body {{margin: 0;padding: 0;}}
img {{

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}}
table {{

border-collapse: collapse !important;
}}
body {{

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}}

appleBody a {{

color: #68440a;

text-decoration: none;
}}
.appleFooter a {{

color: #999999;

text-decoration: none;
}}
.faq {{

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}}
.mobile-only {{

display: none;
}}
.img-apps {{ padding:0 5px 0 0;}}

a.mobile-button:link, a.mobile-button:visited {{ color:#fff!important;}}

@media screen and (max-width: 525px) {{

table[class="wrapper"] {{

width: 100% !important;
}}

td[class="logo"] {{

text-align: left;

padding: 20px 0 20px 0 !important;
}}
td[class="logo"] img {{

margin: 0 auto!important;
}}

[class="mobile-only"] {{

display: block;
}}

br[class="mobile-hide"] {{

display: none;
}}
td[class="mobile-hide"] {{

display: none;
}}
img[class="mobile-hide"] {{

display: none !important;
}}
img[class="img-max"] {{

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}}

img[class="img-min"] {{

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}}

img[class="img-apps"] {{

max-width: 46% !important;

width: 46% !important;

height: auto !important;

padding:0 2px;
}}
img[class="img-max-profile"] {{

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}}

table[class="responsive-table"] {{

width: 100%!important;
}}

td[class="padding"] {{

padding: 10px 5% 15px 5% !important;
}}
td[class="amount"] {{

font-size: 9px!important;
}}
td[class="mobile-text-twelve"] {{

font-size: 12px!important;
}}
span[class="mobile-text-twelve"] {{

font-size: 14px!important;
}}
td[class="padding-copy"] {{

padding: 10px 5% 10px 5% !important;

text-align: center;
}}
td[class="padding-meta"] {{

padding: 30px 5% 0px 5% !important;

text-align: center;
}}
td[class="no-pad"] {{

padding: 0 0 20px 0 !important;
}}
td[class="no-pad-bottom"] {{

padding: 25px 0 0 0 !important;
}}
td[class="no-padding"] {{

padding: 0 !important;
}}
td[class="section-padding"] {{

padding: 25px 15px 25px 15px !important;
}}
td[class="section-no-padding-bottom"] {{

padding: 25px 15px 0 15px !important;
}}

td[class="section-no-padding-top"] {{

padding: 0 5% 25px 5% !important;
}}

td[class="section-no-padding-top-bottom"] {{

padding: 0 5% 0 5% !important;
}}
td[class="section-padding-bottom-image"] {{

padding: 50px 15px 0 15px !important;
}}

td[class="mobile-wrapper"] {{

padding: 10px 5% 15px 5% !important;
}}
table[class="mobile-button-container"] {{

margin: 0 auto;

width: 100% !important;
}}
a[class="mobile-button"] {{

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}}
}}

Earn $100 in 1 minute.

How?

Simply try our new social network for only 50 seconds...

..and give us your feedback in less than 10 seconds.

Give me $100 (start the clock) &#9658;

Your empowr account was reserved for you by anthony.miller.csn@gmail.com. In order to store your gift however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything.

While your account is very new, if you fail to sign in for just a few days, it will be deleted to eliminate unwanted emails for you, so click a button in emails periodically to notify the system of your desire to keep it active. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVndh%2BWZPozm1D8pGhgZPOKGLIcws7RZylhk7%2BFRFQivlX%2F4uVLGyj5zjGgqHmUsxkjUvEIQymJace5jm1BXmPyXJx57nLfmPDHs26jEDB5qS0LTPP6ZdiedqAfrnjfcmlrzACVf1NbBEq&vet=724&mlid=9292561831.

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: empowr Terms and Conditions. You can prevent future emails here. You can change your password here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by AnthonyMDev** [comment]
body { margin:0 !important; }
div[style*="margin: 16px 0"] { margin:0 !important; font-size:100% !important; }
#outlook a {

padding: 0;
}
ReadMsgBody {

width: 100%;
}
ExternalClass {

width: 100%;
}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {margin: 0;padding: 0;}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
appleFooter a {

color: #999999;

text-decoration: none;
}
faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
mobile-only {

display: none;
}
img-apps { padding:0 5px 0 0;}

a.mobile-button:link, a.mobile-button:visited { color:#fff!important;}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;

padding:0 2px;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 9px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

has invited you to this exclusive free trial
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=15&amp;authToken=29mHx4BOBXmkPI3jGZ1qKK3nYTVn%2b9rf8WpGSdOBgYep%2f%2fbmbgGOZUgmuZBl90v4jm8wNTElbeQSO2BMPnqTWno%2bCfqDTnTgfmVqa7MnB93l46Ak03PgkgwmTzOaIc3hP6ml2vfalltPbBaHZOl7x0TayuYkosC%2frnDJB9dec6mMzl264FIgudcVYfQVenPCUp3f%2bM5C3CQP78rWWvFid2ti6ML%2fx5bTmXmGzSmCJPPH4TmOj8ragz3Fa2TsyOvR2Z1CXMCTv23ffAk9%2bvOAegkRqRIMRuoYnb1uiumB2QMamiBMBqRoXiGRNrZGYzaM&amp;PolicyAcceptance=RaGzIMwZpas%2bHmr%2fY%2fXgkX4DXXr%2bK938lvAgVoN%2f2Jj5%2bS60k1sEfcyhK72b5YjYgsSg1ek3AuAsnywr%2bphkEe9nId75n%2bRbawVkhOE8uZB291d7Jfn1278Rw19ZvHjtEfXE34X7UBr8H2oY8kQO107%2fsFpAgao9Ywo9Y1mjQ3jAvykhOBfGZ9O6NZKwl9UaKa5e1iE%2fOMOSjqyXmsx7HuoP5EBKggu2xJMb%2bemLHeQiUocudNXEeug6KJ%2bQa1b2KrjrQlSGAPOVE0MFGeJqIXb0O6LweS3A7qKhWXfibjBSjUpmi75Y3YIHxNOnW4OxuELPKCCgdEH%2fboxOn6OjLxP90CiQNqq4iNXCjIx2qFPopq8mrKG6y9hqsOgH5beCWzftd4bBxPp7zb72mrog%2bOhWGzl9e1fp%2bvfEGPxCuaTYf8Mv9Gbtm2NGNR7iR3%2bMvssLxk7a%2f4hSTWX%2fGTp6fl6CkYxVx4yzZTeL5skS4WMppttSYcib%2bVPVbIqKNNag5kyAKyQLQ%2boRiLlbGAxUXBCTov1fRfWFBep2Qj2eV1E9L%2fUj0mwS8vofZekOPFQ9x5Kj96VrHGDkCqlElP%2frHlfyKRF8qdjrBo8rZvKeooaBmEeRlZHcRtZHz9hEA%2btchQuoWj54erkLCmHubCaFQFmN6JYr3yVUvmJ0FWk%2ba4KH%2btIgcBbB8LEMy89dcO2hjyq24CQwE0XxGRNd9O%2fZKLLJRE1LpwYc391tyojfbouHlO%2bDKEPtCIypHeJGItaWRioBVZxg%2bST%2bMMzfmQNWNK8UeMQpanRL5z6BLSm25%2bmktTR6NAMbZAQP%2fTaDfAyJNNTwXXnfRfhD%2bufeCDMHjC0i84kp08UbqSs5LOy4N3EFznlQ2nqNfJV3jDyDeVw2sWhYXY04XSCOc5Og510TAhJAyVdO0YX4oN7qn3P76371TiMWDfQ1qVEUlET%2f%2bVX6&amp;vet=745&amp;dt=111817&amp;mlid=10031189224&amp;tmpID=3340&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=40457836&amp;rt=13:

Your account was reserved for you by  in order to reserve your free trial, however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVndh%2BWZPozm1D8pGhgZPOKGLIcws7RZylhk7%2BFRFQivlX%2F4uVLGyj5zjGgqHmUsxkjUvEIQymJace5jm1BXmPyXJx57nLfmPDHs26jEDB5qS0LTPP6ZdiedqAfrnjfcmlrzACVf1NbBEq&vet=745&mlid=10031189224.

No more emails from  ()? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVndh%2BWZPozm1D8pGhgZPOKGLIcws7RZylhk7%2BFRFQivlX%2F4uVLGyj5zjGgqHmUsxkjUvEIQymJace5jm1BXmPyXJx57nLfmPDHs26jEDB5qS0LTPP6ZdiedqAfrnjfcmlrzACVf1NbBEq&vet=745&mlid=10031189224

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: empowr Terms and Conditions. You can prevent future emails here. You can change your password here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA
