### ISSUE TITLE
Make Compatible with OSX

### ISSUE THREAD

**Issue by frankrue** [AnthonyMDev/AmazonS3RequestManager#8]
After cursory review, it seems like it wouldn't take much to make this OSX compatible, like AlamoFire is already. Is this a possibility?

**Comment by AnthonyMDev** [comment]
@frankrue, this seems like a great idea. I'm actually very unfamiliar with OS X development myself, but if need be, I could look into it. I see that you've made a fork and started work on this. I'd definitely be willing to look at a PR when you're finished.

My primary concern: right now, you need `MobileCoreServices` to get the MIME type. If there is an OS X compatible library to do this, then we should be able to make this work.

**Comment by frankrue** [comment]
I'll be honest, here: I don't know a tremendous amount about what I'm doing with framework builds. I was able to get it working locally, but likely only because I'm using the putObject() function ONLY right now. I'm about to implement the getObject() function, and, at that point, I imagine, I will run into the MobileCoreServices problem. I'm sure there's an adequate replacement in OSX. I'll keep you posted.

**Comment by AnthonyMDev** [comment]
@frankrue Thanks for the updates. If you run into a problem you can't solve on your own, let me know and I'll look into it as well. This library definitely should support OS X ASAP.

**Comment by AnthonyMDev** [comment]
@frankrue It looks like on your fork, you were able to remove `MobileCoreServices`. Is your branch working properly for OS X? If so I'll probably make a pull sometime soon.

**Comment by frankrue** [comment]
I am now using this actively without any problems. If you want to pull, let's go for it. Let me know what I need to do.

**Comment by AnthonyMDev** [comment]
Thanks for the quick reply! That's all I need from you. I'll check out the code base and make a pull. I appreciate the work you did!

**Comment by ghost** [comment]
+1

**Comment by AnthonyMDev** [comment]
Version `0.10.0` has been released which includes OS X support!

**Comment by AnthonyMDev** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

anthony.miller.csn@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Resources:

What is empowr?
Who's behind it?
See who you know that's on empowr

No more emails from anthony.miller.csn@gmail.com (anthony.miller.csn@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnTXj17%2F%2F6551qIM2mPLi6mkN0fsS8mo%2FfHOve1kyiE6BT1NpTcodiBCcNOu61nBp3%2BwIP%2BrxC7MLOOn6MrYiF83WajLSqBKuzDBP0UBqubyTq9rqQnMjtpUXUclVT7MSafI1dMkQX5Tl&vet=694&mlid=8998552431&fn=QpLpyL23t7HpRXkzIHngtg%3D%3D

*This offer has been sent by anthony.miller.csn@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.

**Comment by AnthonyMDev** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

Yesterday, anthony.miller.csn@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Not sure you know anthony.miller.csn@gmail.com?

View their photos  to see if you recognize them

Resources:

What is empowr?
Who's behind it?
See who you know that's on empowr

No more emails from anthony.miller.csn@gmail.com (anthony.miller.csn@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnTXj17%2F%2F6551qIM2mPLi6mkN0fsS8mo%2FfHOve1kyiE6BT1NpTcodiBCcNOu61nBp3%2BwIP%2BrxC7MLOOn6MrYiF83WajLSqBKuzDBP0UBqubyTq9rqQnMjtpUXUclVT7MSafI1dMkQX5Tl&vet=694&mlid=9006540560&fn=QpLpyL23t7HpRXkzIHngtg%3D%3D

*This offer has been sent by anthony.miller.csn@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.

**Comment by AnthonyMDev** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

Just a friendly reminder that anthony.miller.csn@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Don't know anthony.miller.csn@gmail.com?

Return the $20  so it doesn't go to waste and you're not keeping anthony.miller.csn@gmail.com waiting

Resources:

What is empowr?
Who's behind it?
See who you know that's on empowr

No more emails from anthony.miller.csn@gmail.com (anthony.miller.csn@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnTXj17%2F%2F6551qIM2mPLi6mkN0fsS8mo%2FfHOve1kyiE6BT1NpTcodiBCcNOu61nBp3%2BwIP%2BrxC7MLOOn6MrYiF83WajLSqBKuzDBP0UBqubyTq9rqQnMjtpUXUclVT7MSafI1dMkQX5Tl&vet=694&mlid=9014767831&fn=QpLpyL23t7HpRXkzIHngtg%3D%3D

*This offer has been sent by anthony.miller.csn@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.

**Comment by AnthonyMDev** [comment]
body {{ margin:0 !important; }}
div[style*="margin: 16px 0"] {{ margin:0 !important; font-size:100% !important; }}
#outlook a {{

padding: 0;
}}
.ReadMsgBody {{

width: 100%;
}}
.ExternalClass {{

width: 100%;
}}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {{

line-height: 100%;
}}
body, table, td, a {{

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}}
table, td {{

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}}
img {{

-ms-interpolation-mode: bicubic;
}}

body {{margin: 0;padding: 0;}}
img {{

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}}
table {{

border-collapse: collapse !important;
}}
body {{

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}}

appleBody a {{

color: #68440a;

text-decoration: none;
}}
.appleFooter a {{

color: #999999;

text-decoration: none;
}}
.faq {{

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}}
.mobile-only {{

display: none;
}}
.img-apps {{ padding:0 5px 0 0;}}

a.mobile-button:link, a.mobile-button:visited {{ color:#fff!important;}}

@media screen and (max-width: 525px) {{

table[class="wrapper"] {{

width: 100% !important;
}}

td[class="logo"] {{

text-align: left;

padding: 20px 0 20px 0 !important;
}}
td[class="logo"] img {{

margin: 0 auto!important;
}}

[class="mobile-only"] {{

display: block;
}}

br[class="mobile-hide"] {{

display: none;
}}
td[class="mobile-hide"] {{

display: none;
}}
img[class="mobile-hide"] {{

display: none !important;
}}
img[class="img-max"] {{

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}}

img[class="img-min"] {{

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}}

img[class="img-apps"] {{

max-width: 46% !important;

width: 46% !important;

height: auto !important;

padding:0 2px;
}}
img[class="img-max-profile"] {{

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}}

table[class="responsive-table"] {{

width: 100%!important;
}}

td[class="padding"] {{

padding: 10px 5% 15px 5% !important;
}}
td[class="amount"] {{

font-size: 9px!important;
}}
td[class="mobile-text-twelve"] {{

font-size: 12px!important;
}}
span[class="mobile-text-twelve"] {{

font-size: 14px!important;
}}
td[class="padding-copy"] {{

padding: 10px 5% 10px 5% !important;

text-align: center;
}}
td[class="padding-meta"] {{

padding: 30px 5% 0px 5% !important;

text-align: center;
}}
td[class="no-pad"] {{

padding: 0 0 20px 0 !important;
}}
td[class="no-pad-bottom"] {{

padding: 25px 0 0 0 !important;
}}
td[class="no-padding"] {{

padding: 0 !important;
}}
td[class="section-padding"] {{

padding: 25px 15px 25px 15px !important;
}}
td[class="section-no-padding-bottom"] {{

padding: 25px 15px 0 15px !important;
}}

td[class="section-no-padding-top"] {{

padding: 0 5% 25px 5% !important;
}}

td[class="section-no-padding-top-bottom"] {{

padding: 0 5% 0 5% !important;
}}
td[class="section-padding-bottom-image"] {{

padding: 50px 15px 0 15px !important;
}}

td[class="mobile-wrapper"] {{

padding: 10px 5% 15px 5% !important;
}}
table[class="mobile-button-container"] {{

margin: 0 auto;

width: 100% !important;
}}
a[class="mobile-button"] {{

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}}
}}

Earn $100 in 1 minute.

How?

Simply try our new social network for only 50 seconds...

..and give us your feedback in less than 10 seconds.

Give me $100 (start the clock) &#9658;

Your empowr account was reserved for you by anthony.miller.csn@gmail.com. In order to store your gift however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything.

While your account is very new, if you fail to sign in for just a few days, it will be deleted to eliminate unwanted emails for you, so click a button in emails periodically to notify the system of your desire to keep it active. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnTXj17%2F%2F6551qIM2mPLi6mkN0fsS8mo%2FfHOve1kyiE6BT1NpTcodiBCcNOu61nBp3%2BwIP%2BrxC7MLOOn6MrYiF83WajLSqBKuzDBP0UBqubyTq9rqQnMjtpUXUclVT7MSafI1dMkQX5Tl&vet=724&mlid=9412688028.

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: empowr Terms and Conditions. You can prevent future emails here. You can change your password here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by AnthonyMDev** [comment]
body { margin:0 !important; }
div[style*="margin: 16px 0"] { margin:0 !important; font-size:100% !important; }
#outlook a {

padding: 0;
}
ReadMsgBody {

width: 100%;
}
ExternalClass {

width: 100%;
}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {margin: 0;padding: 0;}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
appleFooter a {

color: #999999;

text-decoration: none;
}
faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
mobile-only {

display: none;
}
img-apps { padding:0 5px 0 0;}

a.mobile-button:link, a.mobile-button:visited { color:#fff!important;}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;

padding:0 2px;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 9px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

has invited you to this exclusive free trial
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=15&amp;authToken=L78dqihA94Rdh8hR%2bxZa322gSeB71syt%2bOK2QwxK1YjLf46ZycT10H3k4QSU9BF6%2bMdrDrwH2Jp1Sy04fUuzFcrQIbuG3Fs174B5h644lUchRX91qZGo7OrjTvpwx7wR%2bXELInGmmu69mivTglyPHIOYHvhdN2jTUn%2fOuGpu7qP5aLiH%2bOlO6QQynqDInclP6cC94DK%2bnIo71sF335ws52MKUYXof9kHFdF3tN0T5M73si0IyUhp8XS%2f6JsE5rJKFWqgWNx38DqdNDykpgvO68Yc3zmm4AF0gzHP66AFFK%2fevj%2fucIhyars%2bStAPzAAJ&amp;PolicyAcceptance=2Jsw2UWkPPxRRwK%2bzvpMtml721FiBaP2nUbk4hRPANj%2fkYkl5cNRtkgqH6jCWYm5hNqD%2b%2fv7QFE%2fhOoIP%2fp3p40IXHgAJjOctmqdKnAnVNnpOzRCktCOSwfXOeymMFxpabPrRok6IkeanwvSGVwTeb8p%2fQI6W%2f2a4bccqn%2fdfEMWu2rT0Wc8DvB3eJHlWewRFk5fHEnBKK7Bb9MuVAwFslfIwbCYw2k60pDZYR%2fHshfu6WFOXufEYfh45kFmsEHW%2fQwcZB9x6Sy5Jtyq2J2dq6sY9%2fNoLOOy6sxaGns%2fBAOF3eYtMRckdQ9E%2fjDb%2bC5rhnuFzOSoKgjfvyIxtOoshEjy15LFe7R4V03JUJ0qnlMTanVPVuQrBoiME84OTGlLyQvfWYrZS6bVXjzoJFAdaK7jGvbwTt1GoqjvUDDBCMG7xKMwmOKrxfWgMhoax4Chlg3%2b1LgBJ6lwyMMOM62sJGIi%2bYSL5i36dvL2k23PU0nY9ElFbPD%2fw2Qb2oAg%2frNYNQucPYEmTTx2rVBNduCN9xeKAI4xvaxIeYhLtlZI4R2lNVNRMWuGd%2f1jK7nNLxObi1Scf%2fO6xQZ5aUIgHTQH%2fi1ajRGs%2fxio8G4BzO1JLIQEfdhh%2bwhLvcKPP3am0o6I7d2%2fHTWgIChmr6w9aTTdJF9xvCXYPIlQmrbtUOU5Ubg94vDba9TBGmfEet4IuVeSOu3PFu4xvu5ICVhVNaSNozVYKfY5b9kY48D%2fIVPecd7wQcAxE%2fLwwCKCRYmu0IqE12pnkq1RvV56siUWMPhhvH5dky0B%2bAzIBH8%2bM5CzBxF2eaSrSJ56VzjFhtniH1LmPJRDzOdau5BkwTaDW13LV73n4mdAH%2fFuWgLRvzJCxUb8JPQDvJ0CQvNo93Sq5Tm%2bfFN92z6gG7OvipX3dQywy9go5rHlQL6IEoEmi%2fc0FScx%2fvXbuPW8eOpo4Bl%2fWM8KeahhnuingqHDYF7YUeyDmg%3d%3d&amp;vet=745&amp;dt=111817&amp;mlid=10031189190&amp;tmpID=3340&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=40457796&amp;rt=14:

Your account was reserved for you by  in order to reserve your free trial, however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnTXj17%2F%2F6551qIM2mPLi6mkN0fsS8mo%2FfHOve1kyiE6BT1NpTcodiBCcNOu61nBp3%2BwIP%2BrxC7MLOOn6MrYiF83WajLSqBKuzDBP0UBqubyTq9rqQnMjtpUXUclVT7MSafI1dMkQX5Tl&vet=745&mlid=10031189190.

No more emails from  ()? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnTXj17%2F%2F6551qIM2mPLi6mkN0fsS8mo%2FfHOve1kyiE6BT1NpTcodiBCcNOu61nBp3%2BwIP%2BrxC7MLOOn6MrYiF83WajLSqBKuzDBP0UBqubyTq9rqQnMjtpUXUclVT7MSafI1dMkQX5Tl&vet=745&mlid=10031189190

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: empowr Terms and Conditions. You can prevent future emails here. You can change your password here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA
